name: Main
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.x
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test
  # test-browser-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: pnpm/action-setup@v2.0.1
  #       with:
  #         version: 6.32.x
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #         cache: 'pnpm'
  #     - run: pnpm install
  #     - run: npx playwright install --with-deps
  #     - run: pnpm run test-browser
  #     - run: pnpm run test-browser -- --browser firefox
  #     - run: pnpm run test-browser -- --browser webkit
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
      - test
      # - test-browser-linux
    steps:
      # - uses: google-github-actions/release-please-action@v3
      #   id: release
      #   with:
      #     release-type: node
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.x
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm run docs
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs
      - run: pnpm run lint
      - run: pnpm -r publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
